version: '3.4'

services:
  fias:
    container_name: fias
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP2_PORT=${HTTP2_PORT}
      - HOST_API=${HOST_API}
      - HOST=fias
    networks:
      - network
    depends_on:
      - rabbitmq

  opera:
    container_name: opera
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP2_PORT=${HTTP2_PORT}
      - HOST_API=${HOST_API}
      - TZ=Europe/Moscow
      - HOST=opera
    networks:
      - network
    depends_on:
      - rabbitmq

  sanatorium:
    container_name: sanatorium
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP2_PORT=${HTTP2_PORT}
      - HOST_API=${HOST_API}
      - HOST=sanatorium
    networks:
      - network
    depends_on:
      - rabbitmq

  hostapi:
    container_name: hostapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=${HTTP1_PORT}
      - HTTP1_PORT=${HTTP1_PORT}
      - HTTP2_PORT=${HTTP2_PORT}
    ports:
      - 8080:${HTTP1_PORT}
    networks:
      - network
    depends_on:
      - rabbitmq
  
  elasticsearch:
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:Z
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - network
    depends_on:
      - rabbitmq
  
  kibana:
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      - network
    depends_on:
      - elasticsearch

  rabbitmq:
    container_name: rabbitmq
    ports:
      - "15672:15672"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
    elasticsearch:

