version: '3.4'

services:
  fias:
    image: ${DOCKER_REGISTRY-}fias
    build:
      context: .
      dockerfile: src/Bridge.Fias/Dockerfile

  opera:
    image: ${DOCKER_REGISTRY-}opera
    build:
      context: .
      dockerfile: src/Bridge.Opera/Dockerfile

  sanatorium:
    image: ${DOCKER_REGISTRY-}sanatorium
    build:
      context: .
      dockerfile: src/Bridge.Sanatorium/Dockerfile

  hostapi:
    image: ${DOCKER_REGISTRY-}hostapi
    build:
      context: .
      dockerfile: src/Bridge.HostApi/Dockerfile
  
  spa:
    build:
      context: .
      dockerfile: src/bridge-spa/Dockerfile
  
  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
  
  kibana:
    image: kibana:${ELASTIC_VERSION}

  rabbitmq:
    image: rabbitmq:3.12.12-management-alpine
  
  nginx:
    image: nginx

