services:
  bridge.fias:
    image: ${DOCKER_REGISTRY-}bridge_fias
    build:
      context: .
      dockerfile: src/Bridge.Fias/Dockerfile

  bridge.opera:
    image: ${DOCKER_REGISTRY-}bridge_opera
    build:
      context: .
      dockerfile: src/Bridge.Opera/Dockerfile

  bridge.sanatorium:
    image: ${DOCKER_REGISTRY-}bridge_sanatorium
    build:
      context: .
      dockerfile: src/Bridge.Sanatorium/Dockerfile

  bridge.fiscal:
    image: ${DOCKER_REGISTRY-}bridge_fiscal
    build:
      context: .
      dockerfile: src/Bridge.Fiscal/Dockerfile

  bridge.telegrambot:
    image: ${DOCKER_REGISTRY-}bridgetelegrambot
    build:
      context: .
      dockerfile: src/Bridge.TelegramBot/Dockerfile

  bridge.hostapi:
    image: ${DOCKER_REGISTRY-}bridge_hostapi
    build:
      context: .
      dockerfile: src/Bridge.HostApi/Dockerfile
  
  bridge.spa:
    build:
      context: .
      dockerfile: src/bridge-spa/Dockerfile
  
  postgres:
    image: postgres:16.3-alpine3.20
  
  elasticsearch:
    image: elasticsearch:8.12.0

  rabbitmq:
    image: rabbitmq:3.13.3-alpine
  
  redis:
    image: redis:7.4-rc2-alpine3.20
