version: '3.4'

services:
  fias:
    container_name: fias
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP2_PORT=${HTTP2_PORT}
      - HOST_API=${HOST_API}
      - HOST=fias
    networks:
      - network
    depends_on:
      - rabbitmq
    restart: always

  opera:
    container_name: opera
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP2_PORT=${HTTP2_PORT}
      - HOST_API=${HOST_API}
      - TZ=Europe/Moscow
      - HOST=opera
    networks:
      - network
    depends_on:
      - rabbitmq

  sanatorium:
    container_name: sanatorium
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP2_PORT=${HTTP2_PORT}
      - HOST_API=${HOST_API}
      - HOST=sanatorium
    networks:
      - network
    depends_on:
      - rabbitmq
    restart: always

  hostapi:
    container_name: hostapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=${HTTP1_PORT}
      - HTTP1_PORT=${HTTP1_PORT}
      - HTTP2_PORT=${HTTP2_PORT}
    ports:
      - 8080:${HTTP1_PORT}
    networks:
      - network
    depends_on:
      - rabbitmq
    restart: always
  
  spa:
    container_name: spa
    volumes:
      - bridge-spa:/app/build
  
  elasticsearch:
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:Z
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - network
    depends_on:
      - rabbitmq
    restart: always
  
  kibana:
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      - network
    depends_on:
      - elasticsearch
    restart: always

  rabbitmq:
    container_name: rabbitmq
    ports:
      - "15672:15672"
    networks:
      - network
    restart: always
  
  nginx:
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - bridge-spa:/usr/share/nginx/html
    depends_on:
      - spa
    restart: always

networks:
  network:
    driver: bridge

volumes:
  elasticsearch:
  bridge-spa:

