global using Bridge.Fias.Entities;
global using Bridge.Fias.Interface;
global using Bridge.Fias.SocketClient;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Options;
global using System.Net;
global using System.Net.Sockets;
global using System.Text;
