global using Bridge.Extensions.Logging;
global using Bridge.EventBus.Messages.Base;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json;
global using RabbitMQ.Client;
global using RabbitMQ.Client.Events;
global using System.Text;
