global using Bridge.Extensions.Logging;
global using Google.Protobuf.WellKnownTypes;
global using Grpc.Core;
global using Grpc.Net.Client;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Newtonsoft.Json;
